-- ----------------------------
--  table structure for events
-- ----------------------------
drop table if exists events;
create table events (
    game_id char(12) not null,
    away_team_id char(3) not null,
    inn_ct int not null,
    bat_home_id int not null,
    outs_ct int not null,
    balls_ct int not null,
    strikes_ct int not null,
    pitch_seq_tx varchar(40) not null,
    away_score_ct int not null,
    home_score_ct int not null,
    bat_id char(8) not null,
    bat_hand_cd char(1) not null,
    resp_bat_id char(8) not null,
    resp_bat_hand_cd char(1) not null,
    pit_id char(8) not null,
    pit_hand_cd char(1) not null,
    resp_pit_id char(8) not null,
    resp_pit_hand_cd char(1) not null,
    pos2_fld_id char(8) not null,
    pos3_fld_id char(8) not null,
    pos4_fld_id char(8) not null,
    pos5_fld_id char(8) not null,
    pos6_fld_id char(8) not null,
    pos7_fld_id char(8) not null,
    pos8_fld_id char(8) not null,
    pos9_fld_id char(8) not null,
    base1_run_id varchar(8) not null,
    base2_run_id varchar(8) not null,
    base3_run_id varchar(8) not null,
    event_tx varchar(100) not null,
    leadoff_fl boolean not null,
    ph_fl boolean not null,
    bat_fld_cd int not null,
    bat_lineup_id int not null,
    event_cd int not null,
    bat_event_fl boolean not null,
    ab_fl boolean not null,
    h_cd int not null,
    sh_fl boolean not null,
    sf_fl boolean not null,
    event_outs_ct int not null,
    dp_fl boolean not null,
    tp_fl boolean not null,
    rbi_ct int not null,
    wp_fl boolean not null,
    pb_fl boolean not null,
    fld_cd int not null,
    battedball_cd char(1) not null,
    bunt_fl boolean not null,
    foul_fl boolean not null,
    battedball_loc_tx varchar(5) not null,
    err_ct int not null,
    err1_fld_cd int not null,
    err1_cd char(1) not null,
    err2_fld_cd int not null,
    err2_cd char(1) not null,
    err3_fld_cd int not null,
    err3_cd char(1) not null,
    bat_dest_id int not null,
    run1_dest_id int not null,
    run2_dest_id int not null,
    run3_dest_id int not null,
    bat_play_tx varchar(8) not null,
    run1_play_tx varchar(15) not null,
    run2_play_tx varchar(15) not null,
    run3_play_tx varchar(15) not null,
    run1_sb_fl boolean not null,
    run2_sb_fl boolean not null,
    run3_sb_fl boolean not null,
    run1_cs_fl boolean not null,
    run2_cs_fl boolean not null,
    run3_cs_fl boolean not null,
    run1_pk_fl boolean not null,
    run2_pk_fl boolean not null,
    run3_pk_fl boolean not null,
    run1_resp_pit_id varchar(8) not null,
    run2_resp_pit_id varchar(8) not null,
    run3_resp_pit_id varchar(8) not null,
    game_new_fl boolean not null,
    game_end_fl boolean not null,
    pr_run1_fl boolean not null,
    pr_run2_fl boolean not null,
    pr_run3_fl boolean not null,
    removed_for_pr_run1_id varchar(8) not null,
    removed_for_pr_run2_id varchar(8) not null,
    removed_for_pr_run3_id varchar(8) not null,
    removed_for_ph_bat_id varchar(8) not null,
    removed_for_ph_bat_fld_cd int not null,
    po1_fld_cd int not null,
    po2_fld_cd int not null,
    po3_fld_cd int not null,
    ass1_fld_cd int not null,
    ass2_fld_cd int not null,
    ass3_fld_cd int not null,
    ass4_fld_cd int not null,
    ass5_fld_cd int not null,
    event_id int not null,
    home_team_id char(3) not null,
    bat_team_id char(3) not null,
    fld_team_id char(3) not null,
    bat_last_id int not null,
    inn_new_fl boolean not null,
    inn_end_fl boolean not null,
    start_bat_score_ct int not null,
    start_fld_score_ct int not null,
    inn_runs_ct int not null,
    game_pa_ct int not null,
    inn_pa_ct int not null,
    pa_new_fl boolean not null,
    pa_trunc_fl boolean not null,
    start_bases_cd int not null,
    end_bases_cd int not null,
    bat_start_fl boolean not null,
    resp_bat_start_fl boolean not null,
    bat_on_deck_id varchar(8),
    bat_in_hold_id varchar(8) not null,
    pit_start_fl boolean not null,
    resp_pit_start_fl boolean not null,
    run1_fld_cd int not null,
    run1_lineup_cd int not null,
    run1_origin_event_id int not null,
    run2_fld_cd int not null,
    run2_lineup_cd int not null,
    run2_origin_event_id int not null,
    run3_fld_cd int not null,
    run3_lineup_cd int not null,
    run3_origin_event_id int not null,
    run1_resp_cat_id varchar(8) not null,
    run2_resp_cat_id varchar(8) not null,
    run3_resp_cat_id varchar(8) not null,
    pa_ball_ct int not null,
    pa_called_ball_ct int not null,
    pa_intent_ball_ct int not null,
    pa_pitchout_ball_ct int not null,
    pa_hitbatter_ball_ct int not null,
    pa_other_ball_ct int not null,
    pa_strike_ct int not null,
    pa_called_strike_ct int not null,
    pa_swingmiss_strike_ct int not null,
    pa_foul_strike_ct int not null,
    pa_inplay_strike_ct int not null,
    pa_other_strike_ct int not null,
    event_runs_ct int not null,
    fld_id varchar(8) not null,
    base2_force_fl boolean not null,
    base3_force_fl boolean not null,
    base4_force_fl boolean not null,
    bat_safe_err_fl boolean not null,
    bat_fate_id int not null,
    run1_fate_id int not null,
    run2_fate_id int not null,
    run3_fate_id int not null,
    fate_runs_ct int not null,
    ass6_fld_cd int not null,
    ass7_fld_cd int not null,
    ass8_fld_cd int not null,
    ass9_fld_cd int not null,
    ass10_fld_cd int not null,
    UNKNOWN_OUT_EXC_FL int, 
    UNCERTAIN_PLAY_EXC_FL int
);

create index events_gameid_idx on events (game_id);

-- ----------------------------
--  table structure for games
-- ----------------------------

drop table if exists games;

create table games (
    game_id varchar(12) default null,
    year_id int not null default '0',
    game_dt int default null,
    game_ct int default null,
    game_dy varchar(9) default null,
    start_game_tm int default null,
    dh_fl varchar(1) default null,
    daynight_park_cd varchar(1) default null,
    away_team_id varchar(3) default null,
    home_team_id varchar(3) default null,
    park_id varchar(5) default null,
    away_start_pit_id varchar(8) default null,
    home_start_pit_id varchar(8) default null,
    base4_ump_id varchar(8) default null,
    base1_ump_id varchar(8) default null,
    base2_ump_id varchar(8) default null,
    base3_ump_id varchar(8) default null,
    lf_ump_id varchar(8) default null,
    rf_ump_id varchar(8) default null,
    attend_park_ct int default null,
    scorer_record_id varchar(50) default null,
    translator_record_id varchar(50) default null,
    inputter_record_id varchar(50) default null,
    input_record_ts varchar(18) default null,
    edit_record_ts varchar(18) default null,
    method_record_cd varchar(18) default null,
    pitches_record_cd varchar(1) default null,
    temp_park_ct int default null,
    wind_direction_park_cd int default null,
    wind_speed_park_ct int default null,
    field_park_cd int default null,
    precip_park_cd int default null,
    sky_park_cd int default null,
    minutes_game_ct int default null,
    inn_ct int default null,
    away_score_ct int default null,
    home_score_ct int default null,
    away_hits_ct int default null,
    home_hits_ct int default null,
    away_err_ct int default null,
    home_err_ct int default null,
    away_lob_ct int default null,
    home_lob_ct int default null,
    win_pit_id varchar(8) default null,
    lose_pit_id varchar(8) default null,
    save_pit_id varchar(8) default null,
    gwrbi_bat_id varchar(8) default null,
    away_lineup1_bat_id varchar(8) default null,
    away_lineup1_fld_cd int default null,
    away_lineup2_bat_id varchar(8) default null,
    away_lineup2_fld_cd int default null,
    away_lineup3_bat_id varchar(8) default null,
    away_lineup3_fld_cd int default null,
    away_lineup4_bat_id varchar(8) default null,
    away_lineup4_fld_cd int default null,
    away_lineup5_bat_id varchar(8) default null,
    away_lineup5_fld_cd int default null,
    away_lineup6_bat_id varchar(8) default null,
    away_lineup6_fld_cd int default null,
    away_lineup7_bat_id varchar(8) default null,
    away_lineup7_fld_cd int default null,
    away_lineup8_bat_id varchar(8) default null,
    away_lineup8_fld_cd int default null,
    away_lineup9_bat_id varchar(8) default null,
    away_lineup9_fld_cd int default null,
    home_lineup1_bat_id varchar(8) default null,
    home_lineup1_fld_cd int default null,
    home_lineup2_bat_id varchar(8) default null,
    home_lineup2_fld_cd int default null,
    home_lineup3_bat_id varchar(8) default null,
    home_lineup3_fld_cd int default null,
    home_lineup4_bat_id varchar(8) default null,
    home_lineup4_fld_cd int default null,
    home_lineup5_bat_id varchar(8) default null,
    home_lineup5_fld_cd int default null,
    home_lineup6_bat_id varchar(8) default null,
    home_lineup6_fld_cd int default null,
    home_lineup7_bat_id varchar(8) default null,
    home_lineup7_fld_cd int default null,
    home_lineup8_bat_id varchar(8) default null,
    home_lineup8_fld_cd int default null,
    home_lineup9_bat_id varchar(8) default null,
    home_lineup9_fld_cd int default null,
    away_finish_pit_id varchar(8) default null,
    home_finish_pit_id varchar(8) default null
);

create index games_gameid_idx on games (game_id);

-- ----------------------------
--  table structure for subs
-- ----------------------------

drop table if exists subs;

create table subs (
    game_id varchar(12) default null,
    inn_ct int default null,
    bat_home_id int default null,
    sub_id varchar(8) default null,
    sub_home_id int default null,
    sub_lineup_id int default null,
    sub_fld_cd int default null,
    removed_id varchar(8) default null,
    removed_fld_cd int default null,
    event_id int default null
);